using System;

namespace ConsoleAppCms2025.Model
{
    /// <summary>
    /// Represents a patient appointment with a doctor, including schedule and status.
    /// </summary>
    public class Appointment
    {
        /// <summary>
        /// Unique identifier generated by the database for the appointment.
        /// </summary>
        public int AppointmentId { get; set; }

        /// <summary>
        /// Token number assigned for queue management on the appointment day.
        /// </summary>
        public string TokenNo { get; set; }

        /// <summary>
        /// Date of the appointment (date component only).
        /// </summary>
        public DateTime AppointmentDate { get; set; }

        /// <summary>
        /// Human-readable time slot for the appointment, e.g., "10:30 AM".
        /// </summary>
        public string TimeSlot { get; set; }

        /// <summary>
        /// Type of consultation, e.g., General or Follow-up.
        /// </summary>
        public string ConsultationType { get; set; }

        /// <summary>
        /// MMR number of the patient for whom the appointment is booked.
        /// </summary>
        public string PatientMMR { get; set; }

        /// <summary>
        /// Identifier of the doctor with whom the appointment is scheduled.
        /// </summary>
        public int DoctorId { get; set; }

        /// <summary>
        /// Identifier of the user (staff) who booked the appointment.
        /// </summary>
        public int UserId { get; set; }

        /// <summary>
        /// Indicates whether the appointment record is active.
        /// </summary>
        public bool IsActive { get; set; }

        /// <summary>
        /// Whether the patient has visited the doctor for this appointment.
        /// </summary>
        public bool IsVisited { get; set; }

        /// <summary>
        /// Derived status string of the visit state.
        /// </summary>
        public string VisitStatus => IsVisited ? "Visited" : "Not Visited";
    }
}
